/// Criado a partir de: http://172.21.20.22:52773/csp/healthshare/hsedge/Custom.EHRInterop.Core.Service.SOAP.Service.cls?wsdl=1
Class Custom.EHRInterop.Core.Operation.SOAP.Client.s0.EnsMessagebody Extends (%SerialObject, %XML.Adaptor) [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://www.intersystems.com/hs/custom/sda";

Parameter XMLNAME = "Ens_Messagebody";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Ens_Messagebody";

Storage Default
{
<StreamLocation>^Custom.EHRI26FF.EnsMessagebodyS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
