/// Criado a partir de: http://172.21.20.22:52773/csp/healthshare/hsedge/Custom.EHRInterop.Core.Service.SOAP.Service.cls?wsdl=1
Class Custom.EHRInterop.Core.Operation.SOAP.Client.s0.EnsResponse Extends Custom.EHRInterop.Core.Operation.SOAP.Client.s0.EnsMessagebody [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://www.intersystems.com/hs/custom/sda";

Parameter XMLNAME = "Ens_Response";

Parameter XMLTYPE = "Ens_Response";

Storage Default
{
<Type>%Storage.Serial</Type>
}

}
