Class Custom.EHRInterop.Core.Operation.SOAP.Operation.Response.SaveSDAResponse Extends Ens.Response [ ProcedureBlock ]
{

Property SaveSDAResult As Custom.EHRInterop.Core.Operation.SOAP.Client.s0.SaveSDAResponse1;

Storage Default
{
<Data name="SaveSDAResponseDefaultData">
<Subscript>"SaveSDAResponse"</Subscript>
<Value name="1">
<Value>SaveSDAResult</Value>
</Value>
</Data>
<DefaultData>SaveSDAResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
